<a href="https://colab.research.google.com/github/joydeep-kamdar/PapersRepo/blob/master/Kamdar_Student_Optional_PythonLibraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy, Pandas, Matplotlib and Seaborn, and Sci-Kit Learn

In [ ]:
#@title Run this to prepare your data! { display-mode: "form" }

!wget -q --show-progress "https://storage.googleapis.com/inspirit-ai-data-bucket-1/Data/AI%20Scholars/Sessions%201%20-%205/Session%201%20-%20Python%20Basics%20and%20Libraries/tips.csv"

tips.csv.1          100%[===================>]   7.82K  --.-KB/s    in 0s      


Before we set out on our journey into the land of artificial intelligence, we must first pack some gear.
Some of the essentials include Numpy, Pandas, Matplotlib, and Seaborn. Let's discuss Python Packages first!

### Note: In case of time constraint, only do the sections that have an emoji next to the title.

## What are Python Packages?

A Python package is simply an collection of modules — files consisting of Python code. The packages that we'll be looking at today include Numpy, Pandas, Matplotlib, and Seaborn. Let's begin with NumPy.

# NumPy: An Introduction  🤖

Numpy is the core library for scientific computing in Python. Numpy provides the flexibility to create multidimensional array objects (arrays within arrays) and compute a wide variety of mathematical operations including basic linear algebra, basic statistical operations, random simulation and much more. We will represent all of our data which will be fed into our machine learning models using Numpy.

We'll start with the standard NumPy import, under the alias np:

In [ ]:
import numpy as np

### Arrays 🚖

An **array** is simply a collection of items. At the heart of a Numpy library is the array object or the ndarray object (n-dimensional array).  Simply put, it is a table of elements (usually numbers and the same type) indexed by a tuple of positive integers. In NumPy dimensions are called **axes**. The number of axes is referred to as **rank**.
<br/>
Let's create an 1D array of  **taxi rates** (in dollars) by passing it through a list:

In [ ]:
a = np.array([12.50, 10.20, 25])

We can view the contents of the array by running the following code:

In [ ]:
a

array([12.5, 10.2, 25. ])

Awesome! 👏 Let's now create an multi-dimensional array.

In [ ]:
b = np.array([
    [19.50, 13, 12, 11 ],
    [12.50, 10, 25, 14],
    [12.50, 10, 25, 14]])

In [ ]:
b

array([[19.5, 13. , 12. , 11. ],
       [12.5, 10. , 25. , 14. ]])

## Exercise 1:  Arrays ⛷

**Exercise 1a:**

Create a NumPy single - dimensional array and assign it to a variable that describes the following situation:
- Find the weather for the next 5 days in your favorite city, and enter it into the array.

In [ ]:
w = np.array([82, 75, 87, 92, 84 ])

**Exercise 1b:**

Create another NumPy single - dimensional array and assign it to a variable that describes the following situation:
* Write your 5 favorite numbers.

In [ ]:
f = np.array([46, 23, 18, 17, 5 ])

**Exercise 1c:**
1. Add the two arrays you created!
2. Subtract the two arrays.

In [ ]:
print(w + f)
print(w - f)

[128  98 105 109  89]
[36 52 69 75 79]


### Methods ⛵️

#### 🎉 Let's now explore some of the methods in NumPy: ###

The [**.shape**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) method for nparray returns the dimensions of the given array. For example, `[x].shape` returns the (vertical, horizontal) dimensions of the variable `x`. Let's use `.shape` to find the dimensions of the multi-dimensional array that we've created above:

_Can you guess the shape before running the command?_

In [ ]:
b.shape

(3, 4)

Note that multi-dimensional arrays can also have more than two dimensions. A three-dimensional array, for example, has arrays within arrays within arrays. Calling array.shape on a 3-dimensional array would return three numbers: (num1, num2, num3).

**Make sure you understand the concept of shapes because this will come up again and again throughout your machine learning experience!**

The [**.linspace**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) method is used to return evenly spaced numbers over a specified interval. Let's create an array of 6 integers between 0 and 100 to demonstrate this method:

In [ ]:
np.linspace(100,600,3)

array([100., 350., 600.])

How about if we wanted to decide the step? The [**.arange**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) method allows us to return evenly spaced values within an given interval.

In [ ]:
np.arange(0,16,3)

array([ 0,  3,  6,  9, 12, 15])

Yay! 🙌 What if we didn't want to define the interval or the step? The [**.random.rand**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html) method accomplishes this purpose by creating an array of a specified shape and fills it with random values. Let's create a 4 x 5 array of random floats between 0-1:

In [ ]:
np.random.rand(4,5)

array([[0.87888575, 0.1418235 , 0.51844649, 0.82138705, 0.9074733 ],
       [0.9363611 , 0.7035813 , 0.75761691, 0.191289  , 0.2729663 ],
       [0.81900022, 0.31739872, 0.02010152, 0.00263069, 0.11734307],
       [0.76023193, 0.24015952, 0.87135369, 0.10539421, 0.14132   ]])

If we want to increase the size of the floats between an certain interval (0-100), we can simply multiply by the highest digit in that interval:

In [ ]:
np.random.rand(4,5)*100
d = np.random.rand(4,5)*100

Notice how the numbers when you call the random function are different the second time. This is because it generates new numbers each time.

We can also explore some of the properties of the array. The [**.dtype**](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)  method outputs the type of elements in an given array:

In [ ]:
c = np.arange(0,10,3)

In [ ]:
print(c)
print(c.dtype)
print(c.shape)
print(d.shape)
print(d.dtype)

[0 3 6 9]
int64
(4,)
(4, 5)
float64


Kudos! **int64** simply means that the elements in the array are integers. Remember that NumPy arrays only support an *singular* data type for each array unlike Python arrays. Other data types include **float64** and **double64**, which are used to specify numbers with decimals (**int64**s must be whole numbers).

## Exercise 2: Methods 🏃

###Time to test our skills!

Using the **.shape** method, find the dimensions of the array containing the weather of your favorite city.

In [ ]:
w.shape

(5,)

Use the **.linspace** method to create an array of 5 evenly-spaced integers between 15 and 45.

In [ ]:
p= np.linspace(15,45,5)
print(p)

[15.  22.5 30.  37.5 45. ]


Create a 3x6 array using the **.random.rand()** method.

In [ ]:
np.random.rand(3,6)

array([[0.88341867, 0.67979969, 0.04535767, 0.01840986, 0.83698429,
        0.74232433],
       [0.24755229, 0.56838152, 0.19441143, 0.65831155, 0.63426325,
        0.79373307],
       [0.97556257, 0.75454225, 0.60366077, 0.80133556, 0.81552439,
        0.97000447]])

## Operations

NumPy offers the ability to compute arrays together.

In [ ]:
x = np.array([3,4,5])

In [ ]:
y = np.array([1,2,3])

We can use traditional math symbols to add, subtract, multiply, and divide the two arrays:

In [ ]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x**2)

[4 6 8]
[2 2 2]
[ 3  8 15]
[3.         2.         1.66666667]
[ 9 16 25]


## Scalar Math

We can use basic functions to add, subtract, multiply, divide, and power the array:

_Can you guess the output before running command?_

In [ ]:
np.add(x,1)

array([4, 5, 6])

In [ ]:
np.subtract(x,2)

array([1, 2, 3])

In [ ]:
np.multiply(x,3)

array([ 9, 12, 15])

In [ ]:
np.divide(x,4)

array([0.75, 1.  , 1.25])

In [ ]:
np.power(x,5)

array([ 243, 1024, 3125])

## Indexing, Slicing and Reshaping 🔭

Now, we're going to explore some of the functions in Python. First, let's create an array with 12 numbers using the **arange** method in increments of 5:

In [ ]:
s = np.arange(12)*5 # note this is same as np.arange(0,12,1)*5
s

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

**Indexing** refers to retrieving a specific element of an array. Let's find the 3rd value in the above array:

In [ ]:
s[2]

10

**Note**: The values of an array always start with x[0]. We can also retrieve values within an certain range using the **:** symbol:

In [ ]:
s[2:5]

array([10, 15, 20])

😎 Now, let's try combining two arrays using [**concatenate()**](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html) and add 'a' as rows to the end of 's':

In [ ]:
z = np.concatenate((s,a))
print(z)

[ 0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  12.5 10.2
 25. ]


🙌 How about splitting arrays? We can use the [**.split()**](https://numpy.org/doc/stable/reference/generated/numpy.split.html) method to split the s array in sub-arrays:

In [ ]:
z = np.arange(9.0)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
split_arr = np.split(z, 3)

In [ ]:
split_arr

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

**What do y'all think the shape of the above array is?**

In [ ]:
np.array(split_arr).shape

(3, 3)

In [ ]:
np.array(split_arr)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Exercise: Indexing, Slicing and Reshaping

###Time for a test!

Using the **arange** method, create an array of 5 numbers in increments of 10. Call it 'oreo'.

In [ ]:
oreo = np.arange(5)*10
print(oreo)

[ 0 10 20 30 40]


Retrieve the 3rd number in the above array named 'oreo'.

In [ ]:
oreo[2]

20

Create another array of 5 numbers in increments of 15. Use any method you like and call it 'milk'.

In [ ]:
milk = np.arange(5)*15

Retrieve the 1st number in the above array named 'milk'.

Can you eat those many oreos and drink that many cups of milk? You decide! 🥛

In [ ]:
milk[1]

15

😀 We've completed our review of NumPy! After you take a quick break - walk around, drink water - let's move on to Pandas.

# Pandas: An Introduction 🐼

Pandas is an open source Python package that provides numerous tools for data analysis. Pandas provides </br> fast, flexible, and expressive data structures designed to make working with structured (tabular, multidimensional, potentially heterogeneous) and time series data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.

We'll take look at some of the core ideas in Pandas here. You can learn more about Pandas in their official [documentation](http://pandas.pydata.org).

## [Pandas Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) ❄️

A **Series** is similar to an one dimensional array and can store data of any type. The values of a Pandas Series are mutable but the size of a Series is immutable and cannot be changed.<br>
The first element in the series is assigned the index 0, while the last element is at index N-1, where N is the total number of elements in the series.

Let's first **import** pandas under the common alias **pd**:

In [ ]:
import pandas as pd

### Creating a Pandas Series

We can create a series by invoking the pd.Series( ) method, like this:

In [ ]:
decades = pd.Series(np.array([10,20,30,40,50,60]))

In [ ]:
decades

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

As shown above, the index is assigned values from 0-5.

## Exercise: Pandas Series🎿

Create a Series for the GDP of the following countries:
- Czech Republic: 264.50
- Iraq:	250.07
- Romania: 248.84
- Portugal:	242.83

Tip: See what arguments are available in [pd.Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) and use the countries as the index.

In [ ]:
import pandas as pd
import numpy as np


GDP = pd.Series({'Czech Republic':264.50, 'Iraq': 250.07, 'Romania': 248.84, 'Portugal': 242.83})
GDP['Iraq']

250.07

## [Pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) 🐨

The DataFrame is similar to a table. It organizes data into rows and columns as an two-dimensional data structure. The columns can be of different types, and the size of a DataFrame is modifiable. <br>
Let's create a DataFrame of 14 animals, populated with age, weight, and length. <br> First, let's create a Python dictionary.

In [ ]:
animal_dict = {
     'Animal' : ["Hamster", "Alligator", "Hamster","Cat", "Snake", "Cat","Hamster", "Cat", "Cat", "Snake", "Hamster", "Hamster", "Cat", "Alligator"],
     'Age' : [1,9,4,13,14,10,2,4,14,7,14,2,1,7],
     'Weight': [7,13,8,12,11,8,10,14,9,11,10,10,9,14],
     'Length' : [8,6,9,1,8,9,5,6,6,6,5,3,4,5]
}

Now, let's turn our Python dictionary into a DataFrame:

In [ ]:
animal = pd.DataFrame(animal_dict)
animal

Animal  Age  Weight  Length
0     Hamster    1       7       8
1   Alligator    9      13       6
2     Hamster    4       8       9
3         Cat   13      12       1
4       Snake   14      11       8
5         Cat   10       8       9
6     Hamster    2      10       5
7         Cat    4      14       6
8         Cat   14       9       6
9       Snake    7      11       6
10    Hamster   14      10       5
11    Hamster    2      10       3
12        Cat    1       9       4
13  Alligator    7      14       5

We turned a dictionary into a dataframe! Can you tell which parts of the dictionary became the headers and what became the values?

### Pandas Methods 🐢

Great! 👍 Pandas has many unique methods that we can use for data analysis and filtering. Let's first explore [**.unique( )**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html). This method returns all the unique values in an given series or column:

In [ ]:
pd.unique(animal["Animal"])

array(['Hamster', 'Alligator', 'Cat', 'Snake'], dtype=object)

Let's now look at the [**describe()**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html)  method. This method returns the summary statistics of numerical columns. To return the numerical statistics, we write:

In [ ]:
animal.describe(include=[np.number])

Age     Weight     Length
count  14.000000  14.000000  14.000000
mean    7.285714  10.428571   5.785714
std     5.075258   2.208873   2.259291
min     1.000000   7.000000   1.000000
25%     2.500000   9.000000   5.000000
50%     7.000000  10.000000   6.000000
75%    12.250000  11.750000   7.500000
max    14.000000  14.000000   9.000000

Super simple! 🥳  **np.number** simply returns the numerical columns and excludes other data types. Now, let's attempt to filter columns in Pandas. <br>
To filter in Pandas, we simply use brackets. Let's try one example:

In [ ]:
animal[animal["Weight"] > 10]

Animal  Age  Weight  Length
1   Alligator    9      13       6
3         Cat   13      12       1
4       Snake   14      11       8
7         Cat    4      14       6
9       Snake    7      11       6
13  Alligator    7      14       5

🐍 Python is wonderful because it's so intuitive. We pointed to **animal**, and then to the **"Weight"** column. At this point, we filtered for numbers greater than 10
.

What if we want to find rows between a certain subset? We can use the '&' operator:

In [ ]:
animal[(animal["Length"] > 4) & (animal["Length"] < 8)]

Animal  Age  Weight  Length
1   Alligator    9      13       6
6     Hamster    2      10       5
7         Cat    4      14       6
8         Cat   14       9       6
9       Snake    7      11       6
10    Hamster   14      10       5
13  Alligator    7      14       5

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8785923528690381692, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8785923528690381692, *['Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_8785923528690381692, *['Length'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8785923528690381692, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8785923528690381692, *['Weight'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_8785923528690381692, *['Length'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def categorical_histogram(df, colname, figsize=(2, 1.2), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  _, ax = plt.subplots(figsize=figsize)
  bars = df[colname].value_counts()
  plt.barh(bars.index, bars.values, color=sns.palettes.mpl_palette(mpl_palette_name))
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df_8785923528690381692, *['Animal'], **{})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def scatter_plots(df, colname_pairs, scatter_plot_size=2.5, size=8, alpha=.6):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * scatter_plot_size, scatter_plot_size))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    ax.scatter(df[x_colname], df[y_colname], s=size, alpha=alpha)
    plt.xlabel(x_colname)
    plt.ylabel(y_colname)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df_8785923528690381692, *[[['Age', 'Weight'], ['Weight', 'Length']]], **{})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def violin_plot(df, value_colname, facet_colname, col_width=.3, col_length=3, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  plt.figure(figsize=(col_length, col_width * len(df[facet_colname].unique())))
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df_8785923528690381692, *['Age', 'Animal'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def violin_plot(df, value_colname, facet_colname, col_width=.3, col_length=3, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  plt.figure(figsize=(col_length, col_width * len(df[facet_colname].unique())))
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df_8785923528690381692, *['Weight', 'Animal'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz
df_8785923528690381692 = autoviz.get_registered_df('df_8785923528690381692')

def violin_plot(df, value_colname, facet_colname, col_width=.3, col_length=3, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  plt.figure(figsize=(col_length, col_width * len(df[facet_colname].unique())))
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df_8785923528690381692, *['Length', 'Animal'], **{'inner': 'stick'})
chart

We are almost finished our review of Pandas DataFrames. 🤠 Let's now turn our attention to [**.groupby()**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html). The Groupby method involves grouping data around a particular category and applying analysis. This would be useful if you were interested in answering the question, "What's the average weight of all the snakes, cats, hamsters, and alligators?" To find the average weight of each category of animal, we'll group the animals by animal type and then apply the mean function. We could apply other functions too. We could apply "sum" to add up all the weights, "min" to find the lowest, "max" to get the highest, or "count" just to get a count of each animal type:

In [ ]:
animal_groups = animal.groupby("Animal")
animal_groups['Weight'].mean()

Animal
Alligator    13.5
Cat          10.4
Hamster       9.0
Snake        11.0
Name: Weight, dtype: float64

## Exercise 3: DataFrame 🏃
Open the [UN Dataset.](http://data.un.org/_Docs/SYB/PDFs/SYB60_T03_Population%20Growth,%20Fertility%20and%20Mortality%20Indicators.pdf) Create a DataFrame using:
* **Northern Africa**
* **Sub-Saharan Africa**
* **Eastern Asia**
* **Western Europe**

For these areas and the year 2005, create columns for:
* *Population Rate of Increase*
* *Fertility Rate*
* *Infant Mortality*

In [ ]:
UN_Data = {
            'Countries': ['Northern Africa', 'Sub-Saharan Africa', 'Eastern Asia', 'Western Europe'],
            'Population Rate of Increase': [1.7, 2.7, 0.6, 0.3],
            'Fertility Rate': [3.2, 5.6, 1.5, 1.6],
            'Infant Mortality': [39.3, 87.3, 23.2, 4.3]

}

UNdata = pd.DataFrame(UN_Data)
UNdata

Countries  Population Rate of Increase  Fertility Rate  \
0     Northern Africa                          1.7             3.2   
1  Sub-Saharan Africa                          2.7             5.6   
2        Eastern Asia                          0.6             1.5   
3      Western Europe                          0.3             1.6   

   Infant Mortality  
0              39.3  
1              87.3  
2              23.2  
3               4.3

Using filtering, show the areas that have infant mortality between 30 and 50.

In [ ]:
UNdata[(UNdata["Infant Mortality"] > 30) & (UNdata["Infant Mortality"] < 50) ]


Countries  Population Rate of Increase  Fertility Rate  \
0  Northern Africa                          1.7             3.2   

   Infant Mortality  
0              39.3

Find the max for infant mortality for the four areas.

In [ ]:
UNdata["Infant Mortality"].max()

87.3

With that, we've completed our review of the Python library Pandas. If you have any lingering questions, do ask! You can find more on Pandas on their [official website](https://pandas.pydata.org/).

# Matplotlib: A (Tiny) Introduction 📈

Matplotlib is a Python 2D plotting library which produces  plots, histograms, power spectra, bar charts, errorcharts, scatterplots, etc. with just a few lines of code. Source: [Matplotlib](https://matplotlib.org). <br>
We'll cover only some of the coolest features in this Notebook due to time constraints. You can explore more on the [official website.](https://matplotlib.org/tutorials/index.html)

Let's import the `matplotlib` library under the alias `plt`

In [ ]:
import matplotlib.pyplot as plt

### Pyplot

Pyplot is a module of Matplotlib which provides simple functions to add plot elements like lines, images, text, etc. to the current axes in the current figure.

We'll import the Pyplot module to create a simple plot. We will be using two NumPy arrays - one for the x-coordinates and another for the y-coordinates:

In [ ]:
plt.plot([1,2,3,4],[1,4,9,16]) # plt.plot([x-coordinates], [y-coordinates])
plt.show()

Now, we can add titles, and labels:

In [ ]:
plt.plot([1,2,3,4],[1,4,9,16]) # plt.plot([x-coordinates], [y-coordinates])
plt.title("First Plot")
plt.xlabel("X Label")
plt.ylabel("Y Label")
plt.show()

Another commonly used graph in Machine Learning is the Scatter Plot. Let's create a basic scatterplot in MatPlotLib comparing the distribution of height vs. weight:

In [ ]:
height = np.array([167, 170, 149, 165, 155, 180, 166, 146, 159, 185, 145, 168, 172, 181, 169])
weight = np.array([86,74,66,78,68,79,90,73,70,88,66,84, 67, 84, 77])

#We can set the limit (lower, upper) for the x-axis and the y-axis using xlim and ylim, respectively.
plt.xlim(140, 200)
plt.ylim(60,100)
#A scatterplot can be generated through .scatter(x,y)
plt.scatter(height,weight)
plt.title("Comparing Height vs. Weight")
plt.xlabel("Height")
plt.ylabel("Weight")
plt.show()

## Exercise: MatPlotLib 🏃

Using the data for the animal weights and lengths, create a scatterplot comparing the information.

Note: Remember to properly label the graph (x-axis, y-axis, and title!)

In [ ]:
animal_length = [8,6,9,1,8,9,5,6,6,6,5,3,4,5]
animal_weight = [7,13,8,12,11,8,10,14,9,11,10,10,9,14]

# YOUR CODE HERE

# Seaborn: Another (tiny) introduction 🌊

Let's first import the library for seaborn under the alias sns:

In [ ]:
import seaborn as sns

Let's import a csv file - comma-separated values - that details the total bill costs and the tips. We'll run a scatterplot on this data:

In [ ]:
# Run this code to import the data and read it in using 'pd.read_csv('file')'
tips = pd.read_csv('tips.csv')
ax = sns.scatterplot(x="total_bill", y="tip", data=tips) #plotting it

The scatterplot above does not discriminate between the days of the week. What if we wanted to see the distribution of the data for each day?
<br>
For this, we can consider using a categorical scatterplot with the `.catplot()` method.

In [ ]:
sns.catplot(x="day", y="total_bill", data=tips);

We can go even further! How about we try sorting the time of the day that the customer dined at the restaraunt? Let's use the `swarm` parameter to prevent the points from overlapping and group by time:

In [ ]:
sns.catplot(x="total_bill", y="day", hue="time", kind="swarm", data=tips);

To reiterate, the `hue` parameter allows us to add another dimension to group data by color. The `swarm` parameter helps us to visualize the data more clearly by preventing overlapping points (as opposed to catplot where points with the same data values will lie on top of each other).

## Exercise: Seaborn 🐳

###Time for one of our last exercises!

Create a simple scatterplot comparing size of tip vs. size of table.

In [ ]:
# YOUR CODE HERE

# scikit-learn: A Small Preview 👀

**scikit-learn** is a free software machine learning library for the Python programming language. It features various classification, regression and clustering algorithms including support vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy. Official website: https://scikit-learn.org/ <br>
We'll be building a simple linear regression in Scikit-Learn to demonstrate how the library works at the base level.

## Sneak Peak: Linear Regression 🏡

Linear regression is a linear approach to modeling a relationship between an response variable and an explanatory variable. We will study this in detail in the program!

We'll create a small model that predicts the relationship between expected and true housing prices using the California Housing Dataset:

## Import 📦

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()

#### What is this data?

In [ ]:
# Print the description of the dataset (first 1400 characters)
print(data.DESCR[:1400])

In [ ]:
# data.data are all the houses with their attributes.
# data.target are the corresponding house prices in units of 100K

print("House 1, attributes: ", data.data[0])
print("House 1, price: ", data.target[0])

## Train and Define 🚂

We're going to define our X-axis and Y-axis and fit the model to a Linear Regression model.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target)
clf = LinearRegression()
clf.fit(X_train, y_train)
predicted = clf.predict(X_test)
expected = y_test

## Plot 📊

In [ ]:
plt.figure(figsize=(4, 3))
plt.scatter(expected, predicted)
plt.plot([0, 8], [0, 8], '--k')
plt.axis('tight')
plt.xlabel('True price ($100,000s)')
plt.ylabel('Predicted price ($1000s)')
plt.tight_layout()

Woo! We've just seen a small preview of what Scikit-learn can do. We have the ability to create an accurate ML model with a few lines of code.

We hope you learned something useful, and feel more curious to learn more about AI!